apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-static-web2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
        - name: web2
          image: nthuytrang/static-web2:latest
          ports:
            - containerPort: 80
